# Generated by Django 5.1 on 2024-10-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images/'),
        ),
    ]
